---
title: "Data Cleaning"
output: html_document
---

I used the following code to clean the data and make graphs in [NYC Restaurant Inspections](https://p8105.com/dataset_restaurant_inspections.html).

```{r eval = FALSE}
library(tidyverse)
library(p8105.datasets)
library(plotly)

theme_set(
  ggthemes::theme_fivethirtyeight() + theme(legend.position = "bottom")
  )

scale_colour_discrete = scale_color_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```


```{r eval = FALSE}
library(httr)
library(jsonlite)

get_all_inspections = function(url) {
  
  all_inspections = vector("list", length = 0)
  
  loop_index = 1
  chunk_size = 50000
  DO_NEXT = TRUE
  
  while (DO_NEXT) {
    message("Getting data, page ", loop_index)
    
    all_inspections[[loop_index]] = 
      GET(url,
          query = list(`$order` = "zipcode",
                       `$limit` = chunk_size,
                       `$offset` = as.integer((loop_index - 1) * chunk_size)
                       )
          ) %>%
      content("text") %>%
      fromJSON() %>%
      as_tibble()
    
    DO_NEXT = dim(all_inspections[[loop_index]])[1] == chunk_size
    loop_index = loop_index + 1
  }
  
  all_inspections
  
}

url = "https://data.cityofnewyork.us/resource/43nn-pn8j.json"

nyc_inspections = 
  get_all_inspections(url) %>%
  bind_rows() |> 
  janitor::clean_names()
```


```{r eval=FALSE}
# plot of cuisines by borough
nyc_inspections |> 
  filter(boro != 0) |> 
  group_by(boro, cuisine_description) |> 
  summarize(count = n(), .groups = 'drop') |> 
  plot_ly(
    x = ~cuisine_description, y = ~count, color = ~boro,
    type = "bar", text = ~paste("Borough:", boro, "<br>Count:", count)
  ) |> 
  layout(
    title = "Distribution of Cuisines by Borough in NYC",
    xaxis = list(title = "Cuisine", tickangle = -90, tickfont = list(size = 8)),
    yaxis = list(title = "Count"),
    barmode = 'stack',
    legend = list(orientation = "h", x = 0.5, xanchor = 'center', y = -0.2)
  )
```
 

```{r eval=FALSE}
nyc_inspections |> 
  filter(boro != 0) |> 
  mutate(score = as.numeric(score)) |> 
  group_by(boro) |> 
  filter(score %in% 0:100)  |> 
  plot_ly(
    y = ~score, x = ~boro, color = ~boro,
    type = "box", colors = "viridis") |> 
  layout(
    title = "Distribution of Scores by Borough in NYC",
    xaxis = list(title = "Borough"),
    yaxis = list(title = "Score")
  )
```


```{r}
# score distribution for asian restaurants
```

