---
title: "Plotly"
author: "Maya Krishnamoorthy"
date: "2024-10-22"
output: 
  html_document:
    toc: true
    toc_float: true
---

# Here are some plots.

Today, we will make interactive plots in plotly. We'll make examples using the NYC AirBnB dataset.

```{r}
library(tidyverse)
library(p8105.datasets)
library(plotly)
```

Do some initial data cleaning / subsetting.

```{r}
data(nyc_airbnb)

nyc_airbnb = 
  nyc_airbnb |> 
  mutate(rating = review_scores_location / 2) |>
  select(
    neighbourhood_group, neighbourhood, rating, price, room_type, lat, long) |>
  filter(
    !is.na(rating), 
    neighbourhood_group == "Manhattan",
    room_type == "Entire home/apt",
    price %in% 100:500)
```

Use `plotly` to make some quick plots.

```{r}
nyc_airbnb |>
  mutate(text_label = str_c("Price: $", price, "\nRating: ", rating)) |> 
  plot_ly(
    x = ~lat, y = ~long, type = "scatter", mode = "markers",
    color = ~price, text = ~text_label, alpha = 0.5
  )
```

Next up -- box plot.

```{r}
nyc_airbnb |> 
  mutate(neighbourhood = fct_reorder(neighbourhood, price)) |> 
  plot_ly(
    x = ~neighbourhood, y = ~price, color = ~neighbourhood,
    type = "box", colors = "viridis"
  )
```

Let's do a bar chart with the number of rentals.

```{r}
nyc_airbnb |> 
  count(neighbourhood) |> 
  mutate(neighbourhood = fct_reorder(neighbourhood, n)) |> 
  plot_ly(
    x = ~neighbourhood, y = ~n,
    type = "bar"
  )
```



