---
title: "NYC Restaurant Inspections Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(p8105.datasets)
library(plotly)
library(httr)
library(jsonlite)

theme_set(
  ggthemes::theme_fivethirtyeight() + theme(legend.position = "bottom")
  )

scale_colour_discrete = scale_color_viridis_d
scale_fill_discrete = scale_fill_viridis_d


get_all_inspections = function(url) {
  
  all_inspections = vector("list", length = 0)
  
  loop_index = 1
  chunk_size = 50000
  DO_NEXT = TRUE
  
  while (DO_NEXT) {
    message("Getting data, page ", loop_index)
    
    all_inspections[[loop_index]] = 
      GET(url,
          query = list(`$order` = "zipcode",
                       `$limit` = chunk_size,
                       `$offset` = as.integer((loop_index - 1) * chunk_size)
                       )
          ) %>%
      content("text") %>%
      fromJSON() %>%
      as_tibble()
    
    DO_NEXT = dim(all_inspections[[loop_index]])[1] == chunk_size
    loop_index = loop_index + 1
  }
  
  all_inspections
  
}

url = "https://data.cityofnewyork.us/resource/43nn-pn8j.json"

nyc_inspections = 
  get_all_inspections(url) %>%
  bind_rows() |> 
  janitor::clean_names()
```


Column {data-width=500}
-----------------------

### South Asian Restaurant Grades in NYC

```{r}
library(leaflet)

rest_grade_map = 
  nyc_inspections |> 
  filter(
    grade != "N",
    cuisine_description == c("Bangladeshi", "Indian", "Pakistani"),
    boro != 0) |> 
  mutate(
    latitude = as.numeric(latitude),
    longitude = as.numeric(longitude),
    grade = factor(grade, levels = c("A", "B", "C", "Z", "P"))
  ) |> 
  na.omit(grade)

factpal <- colorFactor(
  palette = "viridis",
  domain = rest_grade_map$grade
)

rest_grade_map |> 
  mutate(click_label = str_c(dba, ", Grade: ", grade)) |> 
  leaflet() |> 
  addProviderTiles(providers$CartoDB.Positron) |> 
  addCircleMarkers(
    ~longitude, ~latitude,
    color = ~factpal(grade), radius = 4, label = ~click_label
  ) |> 
  addLegend("bottomright", pal = factpal, values = ~grade, title = "Grade")
```


Column {data-width=500}
-----------------------

### Distribution of Cuisines by Borough in NYC

```{r}
# plot of cuisines by borough
nyc_inspections |> 
  filter(boro != 0) |> 
  group_by(boro, cuisine_description) |> 
  summarize(count = n(), .groups = 'drop') |> 
  plot_ly(
    x = ~cuisine_description, y = ~count, color = ~boro,
    type = "bar", text = ~paste("Borough:", boro, "<br>Count:", count)
  ) |> 
  layout(
    title = "Distribution of Cuisines by Borough in NYC",
    xaxis = list(title = "Cuisine", tickangle = -90, tickfont = list(size = 8)),
    yaxis = list(title = "Count"),
    barmode = 'stack',
    legend = list(orientation = "h", x = 0.5, xanchor = 'center', y = -0.2)
  )
```
 

### Distribution of Scores by Borough in NYC

```{r}
nyc_inspections |> 
  filter(boro != 0) |> 
  mutate(score = as.numeric(score)) |> 
  group_by(boro) |> 
  filter(score %in% 0:100)  |> 
  plot_ly(
    y = ~score, x = ~boro, color = ~boro,
    type = "box", colors = "viridis") |> 
  layout(
    title = "Distribution of Scores by Borough in NYC",
    xaxis = list(title = "Borough"),
    yaxis = list(title = "Score")
  )
```


